# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField()),
                ('question_answer', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
