# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ',
        ),
    ]
